### ISSUE TITLE
exec should affect function scope

### ISSUE THREAD

**Issue by csvoss** [csvoss/onelinerizer#64]
onelinerizer fails the following test cases:
```
def f():
    exec('a = 5')
    return a
print f()
```
The one-lined code throws an error, whereas the original code prints 5.

Also, this one:
```
def f():
    exec ""
    locals()['a'] = 6
    return a
def g():
    locals()['a'] = 6
    return a
a = 5
print f()
a = 5
print g()
```
The one-lined code prints 5\n5, whereas the original code prints 6\n5.

Discovery of this issue is credited to @tjhance.

**Comment by andersk** [comment]
Welp, that would explain the purpose of [`SymbolTable.is_optimized`](https://docs.python.org/2/library/symtable.html#symtable.SymbolTable.is_optimized). The other construct that would trigger this issue is `from … import *`, once we get around to implementing that (#47).

```
Python 2.7.11+ (default, May  9 2016, 15:54:33) 
[GCC 5.3.1 20160429] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> def f():
...     from os import *
...     locals()['a'] = 6
...     return a
... 
<stdin>:1: SyntaxWarning: import * only allowed at module level
>>> a = 5
>>> print f()
6
>>> 
```

**Comment by andersk** [comment]
Though, as for the test cases with `locals()`, it should be noted that we don’t support `locals()` at all. I’m not sure that’s really possible. But if it is, it’s at least a separate issue.

```
--- ORIGINAL ---------------------------------
def f():
    a = 5
    print locals()
f()

----------------------------------------------
{'a': 5}
--- ONELINED ---------------------------------
(lambda __g, __print: [(f(), None)[1] for __g['f'], f.__name__ in [(lambda : (lambda __l: [(__print(locals()), None)[1] for __l['a'] in [(5)]][0])({}), 'f')]][0])(globals(), __import__('__builtin__').__dict__['print'])
----------------------------------------------
{'__l': {'a': 5}, '__print': <built-in function print>}
```

**Comment by csvoss** [comment]
Yeah, agreed about not supporting locals at all.

This looks good! `eval(compile(...))` is nifty.
