### ISSUE TITLE
non-O(n) runtime?

### ISSUE THREAD

**Issue by csvoss** [csvoss/onelinerizer#66]
Test case: 'print 42' \* 10000

This doesn't seem to run in linear time. It has been hypothesized that this is due to string formatting being slow, as the string-to-insert grows as O(n) and it is inserted O(n) times.

**Comment by HashCode55** [comment]
Hi @csvoss, Your awesome talk at Pycon brought me here! Anyways, I wanted to contribute to the project, any hints from where should I start?  `main.py` looks humongous, and just as a side question is there a reason that all the classes/routines are in a single module?

**Comment by csvoss** [comment]
Hey, glad you're interested!

There's `main.py` that is huge and has most of the logic, and there's `template.py` which does some of the string formatting work. The main reason why `main.py` is so big is that it contains a large class which subclasses `ast.NodeVisitor` in order to implement the logic for each AST node. Feel free to flag if there's any area of the code in particular where you'd like more documentation!
