### ISSUE TITLE
onelinerize.com broken, does not transpile example to one line

### ISSUE THREAD

**Issue by laundmo** [csvoss/onelinerizer#78]
first i tried running it with just a print, to see if it technically could work. it doesn't.
![](https://i.imgur.com/5bcC7Ek.png)
adding the parentheses it was complaining about
![](https://i.imgur.com/Q55obKG.png)
then i tried with the provided exampel
![](https://i.imgur.com/IRejJM9.png)
adding parantheses again
![](https://i.imgur.com/vfqw3S2.png)

**Comment by laundmo** [comment]
as i tested locally, this seems to happen if onelinerizer is installed in a python3 environment instead of python2.

installing and executing onelinerizer on python2 seems to work:
`C:/Python27/python.exe -m pip install onelinerizer`
`C:/Python27/python.exe -m onelinerizer test.py`

**Comment by csvoss** [comment]
Ha, I did "upgrade" the website to Python 3 on July 15 in response to a Heroku runtime deprecation.

Thanks for the report!

**Comment by csvoss** [comment]
Resolved and deployed – thank you so much!
