### ISSUE TITLE
I can do it a lot easier

### ISSUE THREAD

**Issue by jakiki6** [csvoss/onelinerizer#80]
You can do it like exec("\xXX\xXX\xXX\uXXXX"):
def onelinerizer(data):
    s = ""
    for c in data:
        c = hex(ord(c))[2:]
        if len(c) > 2:
            s += "\\u" + c.zfill(4)
        else:
            s += "\\x" + c.zfill(2)
    return "exec('" + s + "')"

**Comment by jakiki6** [comment]
Github deletes spaces. New version:
def onelinerizer(data):
	s = ""
	for c in data:
		c = hex(ord(c))[2:]
		if len(c) > 2:
			s += "\\u" + c.zfill(4)
		else:
			s += "\\x" + c.zfill(2)
	return "exec('" + s + "')"

**Comment by jakiki6** [comment]
Oh i hate it

**Comment by jakiki6** [comment]
`def onelinerizer(data):
	s = ""
	for c in data:
		c = hex(ord(c))[2:]
		if len(c) > 2:
			s += "\\u" + c.zfill(4)
		else:
			s += "\\x" + c.zfill(2)
	return "exec('" + s + "')"`

**Comment by jakiki6** [comment]
`
def onelinerizer(data):
    s = ""
    for c in data:
        c = hex(ord(c))[2:]
        if len(c) > 2:
            s += "\\u" + c.zfill(4)
        else:
            s += "\\x" + c.zfill(2)
    return "exec('" + s + "')"
`

**Comment by jakiki6** [comment]
Github deletes spaces.

exec('\\x64\\x65\\x66\\x20\\x6f\\x6e\\x65\\x6c\\x69\\x6e\\x65\\x72\\x69\\x7a\\x65\\x72\\x28\\x64\\x61\\x74\\x61\\x29\\x3a\\x0a\\x20\\x20\\x20\\x20\\x73\\x20\\x3d\\x20\\x22\\x22\\x0a\\x20\\x20\\x20\\x20\\x66\\x6f\\x72\\x20\\x63\\x20\\x69\\x6e\\x20\\x64\\x61\\x74\\x61\\x3a\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x63\\x20\\x3d\\x20\\x68\\x65\\x78\\x28\\x6f\\x72\\x64\\x28\\x63\\x29\\x29\\x5b\\x32\\x3a\\x5d\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x69\\x66\\x20\\x6c\\x65\\x6e\\x28\\x63\\x29\\x20\\x3e\\x20\\x32\\x3a\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x73\\x20\\x2b\\x3d\\x20\\x22\\x5c\\x5c\\x75\\x22\\x20\\x2b\\x20\\x63\\x2e\\x7a\\x66\\x69\\x6c\\x6c\\x28\\x34\\x29\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x65\\x6c\\x73\\x65\\x3a\\x0a\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x20\\x73\\x20\\x2b\\x3d\\x20\\x22\\x5c\\x5c\\x78\\x22\\x20\\x2b\\x20\\x63\\x2e\\x7a\\x66\\x69\\x6c\\x6c\\x28\\x32\\x29\\x0a\\x20\\x20\\x20\\x20\\x72\\x65\\x74\\x75\\x72\\x6e\\x20\\x22\\x65\\x78\\x65\\x63\\x28\\x27\\x22\\x20\\x2b\\x20\\x73\\x20\\x2b\\x20\\x22\\x27\\x29\\x22') is a example

**Comment by jakiki6** [comment]
[oneline.zip](https://github.com/csvoss/onelinerizer/files/3735875/oneline.zip)

**Comment by jakiki6** [comment]
Example:

exec('\x64\x65\x66\x20\x6f\x6e\x65\x6c\x69\x6e\x65\x72\x69\x7a\x65\x72\x28\x64\x61\x74\x61\x29\x3a\x0a\x20\x20\x20\x20\x73\x20\x3d\x20\x22\x22\x0a\x20\x20\x20\x20\x66\x6f\x72\x20\x63\x20\x69\x6e\x20\x64\x61\x74\x61\x3a\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x63\x20\x3d\x20\x68\x65\x78\x28\x6f\x72\x64\x28\x63\x29\x29\x5b\x32\x3a\x5d\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x69\x66\x20\x6c\x65\x6e\x28\x63\x29\x20\x3e\x20\x32\x3a\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x73\x20\x2b\x3d\x20\x22\x5c\x5c\x75\x22\x20\x2b\x20\x63\x2e\x7a\x66\x69\x6c\x6c\x28\x34\x29\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x65\x6c\x73\x65\x3a\x0a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x73\x20\x2b\x3d\x20\x22\x5c\x5c\x78\x22\x20\x2b\x20\x63\x2e\x7a\x66\x69\x6c\x6c\x28\x32\x29\x0a\x20\x20\x20\x20\x72\x65\x74\x75\x72\x6e\x20\x22\x65\x78\x65\x63\x28\x27\x22\x20\x2b\x20\x73\x20\x2b\x20\x22\x27\x29\x22')

**Comment by MrKioZ** [comment]
well this repo was built under these rules

No newlines allowed. No semicolons, either. No silly file I/O tricks, or eval or exec. Just good, old-fashioned λ.

you can check more about it here https://onelinepy.herokuapp.com/

**Comment by csvoss** [comment]
Yep! There are multiple ways to optimize it, depending on one's artistic proclivities.
