### ISSUE TITLE
Getting "ModuleNotFoundError: No module named '__builtin__' under python3

### ISSUE THREAD

**Issue by chaiatbillipay** [csvoss/onelinerizer#81]
Hi,
Great oneliner generator.

Anyways, when running what is generated under python3, am getting
 ModuleNotFoundError: No module named '__builtin__'

I think this needs to be modded to 'import builtins' instead of 'import __builtin' in the code generation.

Regards,
Chai

**Comment by csvoss** [comment]
Yep, this one's a consequence of https://github.com/csvoss/onelinerizer/issues/70.
