### ISSUE TITLE
Trivialization

### ISSUE THREAD

**Issue by PyMaster22** [csvoss/onelinerizer#84]
At least in python3, you can use `eval`/`exec`. This makes one-liners trivial.

**Comment by csvoss** [comment]
For the goals* of this particular project, ignoring `eval` and `exec` is part of the point.

See e.g.:

> No newlines allowed. No semicolons, either. No silly file I/O tricks, or eval or exec. Just good, old-fashioned λ.

– from http://www.onelinerizer.com/

*Namely, [Fun](https://dwarffortresswiki.org/index.php?title=DF2014:Fun&redirect=no)
